version: '3.3'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    labels:
      - wud.display.name=Homepage
      - wud.display.icon=si:gethomepage
    ports:
      - 3001:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=10.0.0.173:3001,home-server-nas.antonio.rafael.nom.br 
    volumes:
      - homepage_config:/app/config
    restart: unless-stopped

volumes:
  homepage_config: