version: '3.3'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_TAG:-latest}
    container_name: homepage
    labels:
      - wud.display.name=Homepage
      - wud.display.icon=si:gethomepage
    ports:
      - 3001:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.3.21:3001,home-server-nas.antonio.rafael.nom.br,localhost:3001 
    volumes:
      - homepage_config:/app/config
      - /root/homelab/config/homepage/icons:/app/public/icons
    restart: unless-stopped

volumes:
  homepage_config: