# AdGuard DNS VIP — nó PRINCIPAL (192.168.3.21)
# VIP: 192.168.3.23  |  VRRP id 51
global_defs {
    router_id adguard_primary
    script_user root
    enable_script_security
}

vrrp_script chk_adguard {
    script "/etc/keepalived/check_adguard.sh"
    interval 2
    weight -30
    fall 2
    rise 2
}

vrrp_instance ADGUARD_DNS {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass AgDnsV51
    }
    unicast_src_ip 192.168.3.21
    unicast_peer {
        192.168.3.22
    }
    virtual_ipaddress {
        192.168.3.23/26
    }
    track_script {
        chk_adguard
    }
}
