apiVersion: 1

datasources:
  - name: Energia - Detalhado 30d
    uid: energy-raw-30d
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    editable: false
    jsonData:
      dbName: home_energy
      httpMode: GET
      timeInterval: 1s
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Token ${INFLUXDB_GRAFANA_READ_TOKEN}

  - name: Energia - Histórico horário
    uid: energy-hourly-inf
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    editable: false
    jsonData:
      dbName: home_energy
      httpMode: GET
      timeInterval: 1h
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Token ${INFLUXDB_GRAFANA_READ_TOKEN}
